In [107]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

from sklearn import preprocessing
from sklearn.model_selection import cross_val_score

import numpy as np

In [108]:
digitos = load_digits()
#, random_state=42
X_train, X_test, y_train, y_test = train_test_split(digitos.data, digitos.target, test_size=0.3)

In [109]:
scale = preprocessing.StandardScaler().fit(X_train)
X_train = scale.transform(X_train)
X_test = scale.transform(X_test)

In [85]:
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)
LogReg.score(X_test,y_test)
#sc2 = LogReg.score(X_train,y_train)
#Y_pred = LogReg.predict(X_test)

print('Accuracy LogReg: {}'.format(LogReg.score(X_test,y_test)))
#print('Accuracy LogReg: {}'.format(LogReg.score(X_train,y_train)))

Accuracy LogReg: 0.975925925925926


In [86]:
SuVeMa = SVC()
SuVeMa.fit(X_train, y_train)
Y_pred = SuVeMa.predict(X_test)
print('Accuracy SVM: {}'.format(SuVeMa.score(X_test,y_test)))

Accuracy SVM: 0.9888888888888889


In [112]:
RamFor = RandomForestClassifier(n_estimators=40)
RamFor.fit(X_train,y_train)
Y_pred = RamFor.predict(X_test)
print('Accuracy Random Forest: {}'.format(RamFor.score(X_test,y_test)))

Accuracy Random Forest: 0.9740740740740741


In [88]:
kf = KFold(n_splits=3, random_state=2, shuffle=True)
for valores_x, valores_y in kf.split([1,2,3,4,5,6,7,8,9]):
#for valores_x, valores_y in kf.split(digitos.data):
    print(valores_x, valores_y)

[0 2 3 5 7 8] [1 4 6]
[1 4 5 6 7 8] [0 2 3]
[0 1 2 3 4 6] [5 7 8]


In [116]:
from numpy import array
from sklearn.model_selection import KFold
# data sample
data = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
# prepare cross validation
kfold = KFold(3, True, 1)
# enumerate splits
for train, test in kfold.split(data):
	print('train: %s, test: %s' % (data[train], data[test]))

train: [0.1 0.4 0.5 0.6], test: [0.2 0.3]
train: [0.2 0.3 0.4 0.6], test: [0.1 0.5]
train: [0.1 0.2 0.3 0.5], test: [0.4 0.6]


In [117]:
def get_scores(modelo, X_train, X_test, y_train, y_test):
    modelo.fit(X_train,y_train)
    return modelo.score(X_test, y_test)

In [119]:
scores_logreg = []
scores_svm = []
scores_rf = []

for train_index, test_index in kfold.split(digitos.data):
    X_train, X_test, y_train, y_test = digitos.data[train_index], digitos.data[test_index], \
                                       digitos.target[train_index], digitos.target[test_index]

    scale = preprocessing.StandardScaler().fit(X_train)
    X_train = scale.transform(X_train)
    X_test = scale.transform(X_test)
    scores_logreg.append(get_scores(LogisticRegression(),X_train, X_test, y_train, y_test))
    scores_svm.append(get_scores(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_scores(RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test))

In [120]:
print(scores_logreg)
print(scores_svm)
print(scores_rf)

[0.9749582637729549, 0.9632721202003339, 0.9666110183639399]
[0.9782971619365609, 0.9833055091819699, 0.9716193656093489]
[0.9716193656093489, 0.9649415692821369, 0.9699499165275459]


In [125]:
cross_val_score(LogisticRegression(),digitos.data, digitos.target)

C:\Users\ELEAL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ELEAL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [105]:
cross_val_score(SVC(),digitos.data, digitos.target)

array([0.96388889, 0.93055556, 0.94986072, 0.95543175, 0.94707521])

In [106]:
cross_val_score(RandomForestClassifier(n_estimators=40),digitos.data, digitos.target)

array([0.93611111, 0.90833333, 0.95821727, 0.96657382, 0.93871866])